const GET_COUNTRIES = "GET_COUNTRIES"
const GET_COUNTRIESNAME = "GET_COUNTRIESNAME"
const GET_COUNTRIES_DETAIL = "GET_COUNTRIES_DETAIL"
const CREATE_COUNTRIE = "CREATE_COUNTRIE"
const PAGINATE = "PAGINATE"
const ALL_ACTIVITY = "ALL_ACTIVITY"
const ORDER_AZ_ZA = "ORDER_AZ_ZA"
const ORDER_POPULATION = "ORDER_POPULATION"
const FILTER_CONTINENT = "FILTER_CONTINENT"


module.exports = {
    GET_COUNTRIES,
    GET_COUNTRIESNAME,
    GET_COUNTRIES_DETAIL,
    CREATE_COUNTRIE,
    ALL_ACTIVITY,
    PAGINATE,
    ORDER_AZ_ZA,
    ORDER_POPULATION,
    FILTER_CONTINENT
    
}