const GET_COUNTRIES = "GET_COUNTRIES"
const GET_COUNTRIESNAME = "GET_COUNTRIESNAME"
const GET_COUNTRIES_DETAIL = "GET_COUNTRIES_DETAIL"
const CREATE_COUNTRIE = "CREATE_COUNTRIE"


module.exports = {
    GET_COUNTRIES,
    GET_COUNTRIESNAME,
    GET_COUNTRIES_DETAIL,
    CREATE_COUNTRIE
}